task: inference

fast_inference:  # onnx, trt, deploy or Empty
data:
  source: demo/images/inference/image.png
  image_size: ${image_size}
  data_augment: {}
  max_samples: null
nms:
  min_confidence: 0.15
  min_iou: 0.4
  max_bbox: 10000
save_predict: True
render_labels: True
