task: train

defaults:
  - validation: ../validation

epoch: 500

data:
  batch_size: 16
  image_size: ${image_size}
  cpu_num: ${cpu_num}
  shuffle: True
  pin_memory: True
  data_augment:
    # Mosaic: 1
    # MixUp: 1
    # HorizontalFlip: 0.5
    RandomCrop: 0.5
    RandomBrightness:
      prob: 0.5
      factor_range: [0.7, 1.3]
    RandomContrast:
      prob: 0.5
      factor_range: [0.7, 1.3]
    RandomSaturation:
      prob: 0.5
      factor_range: [0.7, 1.3]
    # Albumentations-based: blur/noise/compression
    Blur:
      prob: 0.10
      blur_limit: [3, 7]
    MotionBlur:
      prob: 0.10
      blur_limit: [5, 15]
    GaussianBlur:
      prob: 0.10
      blur_limit: [3, 7]
      sigma_limit: [0.1, 2.0]
    GaussNoise:
      prob: 0.15
      mean: 0.0
      var_limit: [10.0, 50.0]
    ImageCompression:
      prob: 0.25
      quality_range: [40, 90]
    ISONoise:
      prob: 0.20
      intensity: [0.05, 0.15]
      color_shift: [0.01, 0.05]
    # Albumentations-based: weather/lighting
    RandomRain:
      prob: 0.15
      slant_range: [-10, 10]
      drop_length: [15, 30]
      drop_width_range: [1, 2]
      density: [0.002, 0.006]
      blur_value: [3, 5]
      brightness_coefficient: [0.9, 1.0]
    RandomFog:
      prob: 0.10
      fog_coef: [0.3, 0.6]
      alpha_coef: [0.05, 0.1]
    RandomSunFlare:
      prob: 0.10
      src_radius_range: [50, 150]
      src_intensity: [0.6, 1.0]
    RemoveOutliers: 1e-8

optimizer:
  type: SGD
  args:
    lr: 0.01
    weight_decay: 0.0005
    momentum: 0.937
    nesterov: true

loss:
  objective:
    BCELoss: 0.5
    BoxLoss: 7.5
    DFLoss: 1.5
  aux:
    0.25
  matcher:
    iou: CIoU
    topk: 10
    factor:
      iou: 6.0
      cls: 0.5

scheduler:
  type: LinearLR
  warmup:
    epochs: 3.0
  args:
    total_iters: ${task.epoch}
    start_factor: 1
    end_factor: 0.01

ema:
  enable: true
  decay: 0.9999
