path: data/wholebody28
train: train
validation: val

class_num: 28
class_list: ['body', 'adult', 'child', 'male', 'female', 'body_with_wheelchair', 'body_with_crutches', 'head', 'front', 'right-front', 'right-side', 'right-back', 'back', 'left-back', 'left-side', 'left-front', 'face', 'eye', 'nose', 'mouth', 'ear', 'shoulder', 'elbow', 'hand', 'hand_left', 'hand_right', 'knee', 'foot']

auto_download:
